title: Harshith Deshalli Ravi
logo: /assets/image/logo2.png
description: Electrical engineer exploring cybersecurity, AI, Python automation, and IoT. Passionate about learning and applying new technologies to solve problems.
# show_downloads: false
theme: jekyll-theme-minimal
