title: Harshith Deshalli Ravi
logo: /assets/image/logo2.png

description: >
Hi! I'm Harshith, a data science student passionate about Python and uncovering insights from complex data. Currently pursuing a Master's in Data Science with an electrical engineering background. Proficient in Python, Pandas, NumPy, and TensorFlow, I stay updated with the latest data science tech. Through internships and projects, I've honed skills in tackling real-world data challenges, seeking opportunities to make a meaningful impact.
 
# show_downloads: false
theme: jekyll-theme-minimal
