title: Harshith Deshalli Ravi
logo: /assets/img/logo.jpg
description: Electrical engineer exploring cybersecurity, AI, Python automation, and IoT. Passionate about learning and applying new technologies to solve problems.
show_downloads: true
theme: jekyll-theme-minimal
