title: Harshith Deshalli Ravi
logo: /assets/image/logo2.png
description: Passionate data science student with expertise in Python, Pandas, NumPy, and TensorFlow. Seeking to tackle real-world challenges and make a meaningful impact.
theme: jekyll-theme-minimal
